# -*- coding: utf-8 -*-

import os

class Config(object):
    SECRET_KEY = os.environ.get("SECRET_KEY") or "I-am-a-funny-unicorn" # Syntax to enable locally defined (fine-tuned) variables, or default, more generic ones
    SQLALCHEMY_DATABASE_URI = "postgresql://"+os.getenv('POSTGRES_USER')+":"+os.getenv('POSTGRES_PASSWORD')+"@"+os.getenv('POSTGRES_HOST')+":"+os.getenv('POSTGRES_PORT')+"/"+os.getenv('POSTGRES_DB') # TODO: avoid credentials + right adress
    SQLALCHEMY_TRACK_MODIFICATIONS = True # Avoid warnings
    #SESSION_COOKIE_SAMESITE="Lax"
    SESSION_COOKIE_SAMESITE="Strict"

    SESSION_COOKIE_SECURE = True
    REMEMBER_COOKIE_SECURE = True
    SESSION_PERMANENT=True
    SESSION_TYPE = "filesystem"

    SESSION_COOKIE_HTTPONLY = True
    REMEMBER_COOKIE_HTTPONLY = True

    #ENV='development'
    ENV='production'
    DEBUG=False

    DOMAIN=os.getenv("DOMAIN")
    SERVERN=os.getenv("SERVER_NAME")
    SERVER_NAME=SERVERN+"."+DOMAIN
    PORT=443

    # set default button sytle and size, will be overwritten by macro parameters
    BOOTSTRAP_BTN_STYLE='primary'
    BOOTSTRAP_BTN_SIZE='sm'

    # set default icon title of table actions
    BOOTSTRAP_TABLE_VIEW_TITLE='Read'
    BOOTSTRAP_TABLE_EDIT_TITLE='Update'
    BOOTSTRAP_TABLE_DELETE_TITLE='Remove'
    BOOTSTRAP_TABLE_NEW_TITLE='Create'


# TESTING=False
# PROPAGATE_EXCEPTIONS=None
# PRESERVE_CONTEXT_ON_EXCEPTION=None

# PERMANENT_SESSION_LIFETIME=datetime.timedelta(days=31)
# USE_X_SENDFILE=False

# APPLICATION_ROOT='/'
# SESSION_COOKIE_NAME='session'
# SESSION_COOKIE_DOMAIN=None
# SESSION_COOKIE_PATH=None

# SESSION_REFRESH_EACH_REQUEST=True
# MAX_CONTENT_LENGTH=None
# SEND_FILE_MAX_AGE_DEFAULT=None
# TRAP_BAD_REQUEST_ERRORS=None
# TRAP_HTTP_EXCEPTIONS=False
# EXPLAIN_TEMPLATE_LOADING=False
# PREFERRED_URL_SCHEME='http'
# JSON_AS_ASCII=True
# JSON_SORT_KEYS=True
# JSONIFY_PRETTYPRINT_REGULAR=False
# JSONIFY_MIMETYPE='application/json'
# TEMPLATES_AUTO_RELOAD=None
# MAX_COOKIE_SIZE=4093

# BOOTSTRAP_USE_MINIFIED=True
# BOOTSTRAP_CDN_FORCE_SSL=False
# BOOTSTRAP_QUERYSTRING_REVVING=True
# BOOTSTRAP_SERVE_LOCAL=False
# BOOTSTRAP_LOCAL_SUBDOMAIN=None
# SQLALCHEMY_BINDS=None
# SQLALCHEMY_NATIVE_UNICODE=None
# SQLALCHEMY_ECHO=False
# SQLALCHEMY_RECORD_QUERIES=None
# SQLALCHEMY_POOL_SIZE=None
# SQLALCHEMY_POOL_TIMEOUT=None
# SQLALCHEMY_POOL_RECYCLE=None
# SQLALCHEMY_MAX_OVERFLOW=None
# SQLALCHEMY_COMMIT_ON_TEARDOWN=False
# SQLALCHEMY_ENGINE_OPTIONS: {}
