#!/bin/bash
#. $HOME/.bashrc 
. /etc/bash.bashrc;

ID=$1
TileSetPort=$2
Frontend=$3

OUTClient=$HOME/.vnc/out_Client_$(date +%F_%H-%M)
echo $OUTClient $ID $TileSetPort $Frontend $DISPLAY > $OUTClient

export locPORT=$(. /etc/bash.bashrc; python3 -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()' )
echo "Free local port for Frontend from tile $ID: $locPORT" >> ${OUTClient}
if [ X$locPORT == X"" ]; then
   exit 1
fi

#pgrep -fla 6501 |sed -s "s/^\([0-9]*\) .*/\1/" |xargs kill
i=0
while [ true ]; do
    echo ssh -T -N -nf -L $locPORT:localhost:$TileSetPort $Frontend 2>&1 >> ${OUTClient}
  ssh -T -N -nf -L $locPORT:localhost:$TileSetPort $Frontend 2>&1 >> ${OUTClient}

  RET=$?
  echo $i $RET
  if [ $RET -eq 0 ]; then 
    echo "ssh TileClient done"  2>&1 >> ${OUTClient}
    break
  elif [ $i -gt 100 ]; then
    echo "ssh TileClient error"  2>&1 >> ${OUTClient}
    exit 1
  fi
  sleep 1
  i=$((i+1))
done
pgrep -fla ssh  >> ${OUTClient}
#DISPLAY=:1
/usr/bin/python3 /TiledViz/TVConnections/TileClient.py $ID $locPORT >> ${OUTClient} 2>&1

