#!/bin/bash
source ./envDB

export PythonVENV=../TiledVizEnv_${DATE}

docker run -d -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_DB=$POSTGRES_DB -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD --name=$postgresNAME postgres:9.6-alpine

sleep 5
export IPPOSTGRES=${POSTGRES_HOST}

sed -e "s&	ENCRYPTED PASSWORD 'm_test/@03';&	ENCRYPTED PASSWORD '$passwordDB';&" -i TVDatabase/TiledViz.sql

psql -W -h $IPPOSTGRES -U tiledviz -d TiledViz -f TVDatabase/TiledViz.sql
sleep 2
psql -W -h $IPPOSTGRES -U tiledviz -d TiledViz -f TVDatabase/management.sql

source ${PythonVENV}/bin/activate
sqlacodegen postgres://${POSTGRES_USER}:"${POSTGRES_PASSWORD}"@${POSTGRES_HOST}/${POSTGRES_DB} --outfile=TVDatabase/TVDb/models.py

