#!/bin/bash
SSH_FRONTEND=$1
SSHLOGNAME=$2
PORTvnc=$3
TiledvizHost=$4
TiledvizConnectionPort=$5
shift 5
OPTIONS=$@

. /home/myuser/.bashrc

echo "" >> .ssh/config
echo "Host $TiledvizHost" >> .ssh/config
echo "  User myuser" >> .ssh/config
echo "  ProxyCommand ssh ${SSHLOGNAME}@${SSH_FRONTEND} -W %h:%p" >> .ssh/config

# Host desktop.mdls.fr
# User myuser
# ProxyCommand ssh -T -q -o 'ForwardAgent yes' mmancip@mandelbrot-smp.extra.cea.fr 'ssh-add -t 1 && nc %h %p'

COMMANDssh="ssh -o ForwardX11=no -T -N -nf -R \*:${PORTvnc}:localhost:5902 ${OPTIONS} myuser@${TiledvizHost} -p ${TiledvizConnectionPort}"
echo $COMMANDssh

i=0
while [ true ]; do
  ${COMMANDssh} > /home/myuser/.vnc/out_tunnel_ssh 2>&1

  RET=$?
  echo $i $RET
  if [ $RET -eq 0 ]; then 
    echo "ssh done" >> /home/myuser/.vnc/stdout
    break
  elif [ $i -gt 100 ]; then
    echo "ssh error" >> /home/myuser/.vnc/stdout
    RET=$((100+$RET))
    break
  fi
  sleep 1
  i=$((i+1))
done
echo tunnel ssh end >> /home/myuser/.vnc/stdout
exit $RET
