#!/bin/bash
HTTP_FRONTEND=$1
HTTPLOGNAME=$2
shift 2
OPTIONS=$@

. /home/myuser/.bashrc

PORT=$( ssh -T ${HTTPLOGNAME}@${HTTP_FRONTEND} python -c "'import socket; s=socket.socket(); s.bind((\"\", 0)); print(s.getsockname()[1]); s.close()'" )

COMMANDssh="ssh -T -N -nf -R \*:$PORT:localhost:5902 ${OPTIONS} ${HTTPLOGNAME}@${HTTP_FRONTEND}"
echo $COMMANDssh

echo $PORT > /home/myuser/.vnc/port

i=0
while [ true ]; do
  ${COMMANDssh} > /home/myuser/.vnc/out_tunnel_ssh 2>&1

  RET=$?
  echo $i $RET
  if [ $RET -eq 0 ]; then 
    echo "ssh done" >> /home/myuser/.vnc/stdout
    break
  elif [ $i -gt 100 ]; then
    echo "ssh error" >> /home/myuser/.vnc/stdout
    RET=$((100+$RET))
    break
  fi
  sleep 1
  i=$((i+1))
done
echo tunnel ssh end >> /home/myuser/.vnc/stdout
exit $RET
