#!/bin/bash
x11vnc -forever -rfbport 5902 -noncache -cursor arrow -shared -nowf -display :1 -rfbauth /home/myuser/.vnc/passwd -http > /home/myuser/.vnc/x11vnc 2>&1 &
i=0
while [ true ]; do
    sleep 1
    grep PORT=5902 /home/myuser/.vnc/x11vnc
    RET=$?
    if [ $RET -eq 0 ]; then
	echo vnc done >> /home/myuser/.vnc/stdout
	break
    elif [ $i -gt 100 ]; then 
	RET=100+$RET
	echo error vnc >> /home/myuser/.vnc/stdout
	break
    fi
    i=$((i+1))
done
exit $RET
    
