#!/bin/sh
    
cd /home/myuser/
#git clone https://github.com/flambard-took/websockify-other.git websockify-other-flambard-took

cd websockify
#cd websockify-other-flambard-took/c
#make

passwd="x11vnc -showrfbauth ~/.vnc/passwd"
python /opt/build_pem.py $passwd > ~/.vnc/out_ssl 2>&1

./run 5902 localhost:5901 > ~/.vnc/out_websockify 2>&1 &
#python3 ./websockify.py 5902 localhost:5901 &
#./websockify 5902 localhost:5900 &
