#!/bin/sh

cd /home/myuser/
cp -r /TiledViz/TVConnections/websockify ./
#git clone https://github.com/flambard-took/websockify-other.git websockify-other-flambard-took

cd websockify
#cd websockify-other-flambard-took/c
#make

passwd="x11vnc -showrfbauth ~/.vnc/passwd"
python3 /opt/build_pem.py $passwd

./run 5902 localhost:5901 &
#python3 ./websockify.py 5902 localhost:5901 &
#./websockify 5902 localhost:5900 &
