#!/bin/bash
DATE_=$(date +%F_%H-%M-%S)
echo $DATE_
mv TVDatabase/postgresql $HOME/tmp
source $HOME/.cache/envTiledViz
sed -e "s&_NTP_&$NTPserver&"  -e "s&_SMTP_SERVER_&$SMTPserver&" TVConnections/mageianconnect/Dockerfile_i > TVConnections/mageianconnect/Dockerfile
docker buildx build -t mageiaconnect -f TVConnections/mageianconnect/Dockerfile . > $HOME/tmp/out_docker_build_connect_$DATE_ 2>&1
RET=$?
if [ $RET -gt 0 ] ; then
    cat $HOME/tmp/out_docker_build_connect_$DATE_
fi
mv $HOME/tmp/postgresql  TVDatabase
date +%F_%H-%M-%S
exit $RET
