#!/bin/bash
date +%F_%H-%M-%S
mv TVDatabase/postgresql $HOME/tmp
source $HOME/.cache/envTiledViz
sed -e "s&_NTP_&$NTPserver&"  -e "s&_SMTP_&$SMTPserver&" TVConnections/mageianvidia/Dockerfile > TVConnections/mageianvidia/Dockerfile_i
docker build -t mageianvidia:latest -f TVConnections/mageianvidia/Dockerfile_i .
mv $HOME/tmp/postgresql  TVDatabase
date +%F_%H-%M-%S
