#!/bin/sh

echo "Session = " $1 

HOSTFILE=./listhost
# HOST         DISPLAY  LEFT   TOP
echo "mandelbrot-1 0 0 0" > ${HOSTFILE}
echo "mandelbrot-1 1 -1 0" >> ${HOSTFILE}
echo "mandelbrot-2 0 -2 0" >> ${HOSTFILE}
echo "mandelbrot-2 1 -3 0" >> ${HOSTFILE}
echo "mandelbrot-3 0 0 -1" >> ${HOSTFILE}
echo "mandelbrot-3 1 -1 -1" >> ${HOSTFILE}
echo "mandelbrot-4 0 -2 -1" >> ${HOSTFILE}
echo "mandelbrot-4 1 -3 -1" >> ${HOSTFILE}

#APPLINK="http://mandelbrot.extra.cea.fr/wildos/test/TileVizCases_config/$1/TileViz/tileviz.html"

#APPLINK="http://192.168.0.12:5000/join/mandelbrot-desktop_passive_Anonymous_2018-10-11T12:39:28.920410_b'rMkm7KI4c9'"

APPLINK="http://192.168.0.12:5000/join/$1_passive_Anonymous_2018-10-11T12:39:28.920410_b'rMkm7KI4c9'"

#ANATOMIST
#APPSCALE=0.60
# VMD
#APPSCALE=0.52
# TEST
#APPSCALE=1

if [ "X$2" == X"" ]; then
	APPSCALE=0.55
else
	APPSCALE=$2
fi
./killall_Wall
sleep 1
set -vx
./script.sh ${APPLINK} ${APPSCALE}
