# Docker file for flask-based docker

FROM python

# Update python3, install pip3, netstat, virtualenv
ENV DEBIAN_FRONTEND teletype
RUN apt-get update && apt-get install -y apt-utils
RUN apt-get install -y python3-pip net-tools openssh-server nginx socat  && pip3 install --upgrade virtualenv

COPY ./ /TiledViz

RUN pip3 install --upgrade pip && pip install --upgrade pip 

RUN rm -rf /TiledViz/TVFiles/* /TiledViz/envDB

# create and run virtualenv
RUN sed -e 's/#GatewayPorts .*/GatewayPorts yes/' -i /etc/ssh/sshd_config; \
    virtualenv -p python3 flask_venv && \
    /bin/bash -c "source /flask_venv/bin/activate ; \
                  export LC_ALL=C.UTF-8 ; \
                  export LANG=C.UTF-8 ; \
		  pip3 install -r /TiledViz/TVWeb/requirements.txt ;"

ENV SERVER_NAME _SERVER_NAME_
ENV DOMAIN _DOMAIN_
ENV SSLpublic _SSLpublic_
ENV SSLprivate _SSLprivate_

HEALTHCHECK --interval=5m --timeout=10s --retries=1 CMD curl --fail https://$SERVER_NAME.$DOMAIN/test || exit 1

#EXPOSE 5000

ENTRYPOINT ["/TiledViz/TVWeb/FlaskDocker/start_docker_web.sh"]

CMD ["localhost", "6431", "TiledViz", "tiledviz", "m_test/@03", "flaskhost", "1002", "1002", "I-am-a-wonderful-unicorn"]
