# Docker file for flask-based docker

FROM python

# Update python3, install pip3, netstat, virtualenv
ENV DEBIAN_FRONTEND teletype
RUN apt-get update && apt-get install -y apt-utils
RUN apt-get install -y python3-pip net-tools openssh-server nginx socat  && pip3 install --upgrade virtualenv

RUN pip3 install --upgrade pip

COPY ./ /TiledViz

RUN rm -rf /TiledViz/TVFiles/* /TiledViz/envDB

# create and run virtualenv
RUN sed -e 's/#GatewayPorts .*/GatewayPorts yes/' -i /etc/ssh/sshd_config; \
    virtualenv -p python3 flask_venv && \
    /bin/bash -c "source /flask_venv/bin/activate ; \
                  export LC_ALL=C.UTF-8 ; \
                  export LANG=C.UTF-8 ; \
		  pip3 install -r /TiledViz/TVWeb/requirements.txt ;"

HEALTHCHECK CMD curl --fail http://localhost:4999/ || exit 1
EXPOSE 4999

EXPOSE 5000

ENTRYPOINT ["/TiledViz/TVWeb/FlaskDocker/start_docker_web.sh"]

CMD ["localhost", "6431", "TiledViz", "tiledviz", "m_test/@03", "flaskhost", "1002", "1002", "I-am-a-wonderful-unicorn"]
