#!/bin/bash

. /flask_venv/bin/activate

export POSTGRES_HOST=$1
export POSTGRES_PORT=$2
export POSTGRES_DB=$3
export POSTGRES_USER=$4
export POSTGRES_PASSWORD="$5"
export flaskhost=$6
export SMTP_PASSWORD="$7"
shift 7
export SECRET_KEY="$@"

echo "Start flask :  $SECRET_KEY"
sqlacodegen "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?host=${POSTGRES_HOST}" --outfile=/TiledViz/TVWeb/app/models.py 

cd /TiledViz/TVWeb
pwd
# Set locales to avoid encoding problems
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
export FLASK_APP=TVWeb.py
#export FLASK_ENV=development

echo $LC_ALL $LANG $FLASK_APP

gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker --timeout 240 --config gunicorn.conf.py --certfile=$SSLpublic --keyfile=$SSLprivate TVWeb:app

