#!/bin/bash

. /flask_venv/bin/activate

export POSTGRES_HOST=$1
export POSTGRES_DB=$2
export POSTGRES_USER=$3
export POSTGRES_PASSWORD="$4"
export flaskhost=$5
shift 5
export SECRET_KEY="$@"
echo "Start flask :  $SECRET_KEY"
sqlacodegen postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB} --outfile=/TiledViz/TVWeb/app/models.py --flask

cd /TiledViz/TVWeb
pwd
# Set locales to avoid encoding problems
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
export FLASK_APP=TVWeb.py
#export FLASK_ENV=development

echo $LC_ALL $LANG $FLASK_APP
flask run --debugger --host=0.0.0.0

